export const MODULES = {
  DASHBOARD: 'dashboard',
  PRODUCTS: 'products',
  WAREHOUSES: 'warehouses',
  CUSTOMERS: 'customers',
  PURCHASES: 'purchases',
  TRANSFERS: 'transfers',
  RETURNS: 'returns',
  SALES: 'sales',
  RENTAL_ORDERS: 'rental_orders',
  REPORTS: 'reports',
  SCRATCHPAD: 'scratchpad',
  SETTINGS: 'settings'
};

export const PERMISSIONS = {
  VIEW: 'view',
  CREATE: 'create',
  EDIT: 'edit',
  DELETE: 'delete'
};

export const DEFAULT_ROLE_PERMISSIONS = {
  admin: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.PRODUCTS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.WAREHOUSES]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.CUSTOMERS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.PURCHASES]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.TRANSFERS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.RETURNS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.SALES]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.RENTAL_ORDERS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.REPORTS]: [PERMISSIONS.VIEW],
    [MODULES.SCRATCHPAD]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.SETTINGS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE]
  },
  user: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.PRODUCTS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE],
    [MODULES.WAREHOUSES]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE],
    [MODULES.CUSTOMERS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE],
    [MODULES.PURCHASES]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE],
    [MODULES.TRANSFERS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE],
    [MODULES.RETURNS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE],
    [MODULES.SALES]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE],
    [MODULES.RENTAL_ORDERS]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE],
    [MODULES.REPORTS]: [PERMISSIONS.VIEW],
    [MODULES.SCRATCHPAD]: [PERMISSIONS.VIEW, PERMISSIONS.CREATE, PERMISSIONS.EDIT, PERMISSIONS.DELETE],
    [MODULES.SETTINGS]: []
  },
  viewer: {
    [MODULES.DASHBOARD]: [PERMISSIONS.VIEW],
    [MODULES.PRODUCTS]: [PERMISSIONS.VIEW],
    [MODULES.WAREHOUSES]: [PERMISSIONS.VIEW],
    [MODULES.CUSTOMERS]: [PERMISSIONS.VIEW],
    [MODULES.PURCHASES]: [],
    [MODULES.TRANSFERS]: [],
    [MODULES.RETURNS]: [],
    [MODULES.SALES]: [],
    [MODULES.RENTAL_ORDERS]: [],
    [MODULES.REPORTS]: [PERMISSIONS.VIEW],
    [MODULES.SCRATCHPAD]: [PERMISSIONS.VIEW],
    [MODULES.SETTINGS]: []
  }
};
